### ISSUE TITLE
VMCのモーションがUE4で反映されない

### ISSUE THREAD

**Issue by Rhime-design** [HAL9HARUKU/VMC4UE#4]
## ▼問題
UE4.21でVMCのモーション送信を利用しモーキャプを試みましたが、UE4でモーションが反映されませんでした。

### UnrealEngine４
- UE4.21
- VMC4UE、ueOSC：Commits on Jun 13, 2020　Master
https://github.com/HAL9HARUKU/VMC4UE/commit/eefcb38bad93c2211dd3922f6d1b88400e084e9f
- [VRMMapExporter　v0.2.0](https://github.com/HAL9HARUKU/VRMMapExporter/releases/tag/v0.2.0)
- VRM4U for UE4.21
_____
### Unity
- Unity 2018.4.5f1
- UniVRM-0.53.0
_____
### VMCとHMDとモデル
- VirtualMotionCapture0.42r4　～VirtualMotionCapture0.36_3まで
- OculusLinkを使用したOculusQuest
- モデル｜Vroidと市販アバターを元にしたカスタムモデル

## ▼試したこと

1. Unity 2018.4.5f1でUniVRM-0.53.0を使い、VRMモデルを出力。

2. 同VRMモデルを元にVRMMapExporter v0.2.0で.vrmmapを出力。

3. Wikiを参照して「 VMC4UE 」「 VRM4U 」「 ueOSC 」を配置
https://github.com/HAL9HARUKU/VMC4UE/wiki
4. AnimBPを作成
- Modify VMC4UE Bones ノード｜VRMMapping✓　Port8001
- Modify VMC4UE Morph｜VRMMapping✓　Port8001

5. ActorBPを作成→スケルタルメッシュとAniｍBPを設定→レベルに配置

6. VMC→✓OSCでモーション送信を有効にする
Adddress: 127.0.01　Port: 8001
またはAdddress: 127.0.01　Port: 39539など

## ▼結果
→VMCではモーションが反映されましたが、UnrealEngine４では反映されませんでした。
使ったモデルはカスタムモデルですが、AliciaSolidのモデルで試せたら追記します。

## ▼分からないこと
- スケルタルメッシュを格納するBPは、ActorBPで良かったでしょうか？
PawnのBPはCharacterBPなど色々種類があると思うので、指定をお願いできますか？

- Wikiの最後にある「VirtualMotionCapture の使い方」に記載されている
「UE4 で使用したものと同じ VMC を使って VirtualMotionCapture を動かし～」
の「UE4 で使用したものと同じ VMC 」がなにを指しているのかが分かりませんでした。

**Comment by HAL9HARUKU** [comment]
ueOSC の Release が v0.1.0 までしか用意していなかったので v0.2.1 を用意しました。

- ueOSC > Releases > v0.2.1

https://github.com/HAL9HARUKU/ueOSC/releases/tag/v0.2.1

最新の Virtual Motion Capture は OSC を Bundle で送信しているため ueOSC が v0.2.0 以上である必要があります。こちらをお使いください。
それでもうまくいかない場合はファイアウォールやセキュリティーソフトなどにより通信が遮断されていることも考えられますのでそちらの設定をご確認ください。

それから Youtube に使い方の動画をアップしましたので参考になればと思います。

- VMC4UEの使い方

https://youtu.be/_VgB8pPDQaA

> スケルタルメッシュを格納するBPは、ActorBPで良かったでしょうか？

はい、ActorBP で大丈夫です。

> 「UE4 で使用したものと同じ VMC 」がなにを指しているのかが分かりませんでした。

こちら誤記でしたので「UE4 で使用したものと同じ VRM 」に修正しました。
