### ISSUE TITLE
Retargeting in UE to another skeleton

### ISSUE THREAD

**Issue by dpredie** [HAL9HARUKU/VMC4UE#7]
Hi, I am trying to use the VMC4UE to animate another skeleton ( Epic Skeleton or Metahuman, not VRM). 

is there a way to remap/retarget the "Modify VMC4UE Morph" and "VMC4UEVRMMapping"  so it will work on epic skeleton? right now when i retarget, only the root moves. 

https://user-images.githubusercontent.com/33808196/115242733-2fd4c300-a0f0-11eb-9712-5045e0574500.mp4

**Comment by HAL9HARUKU** [comment]
Sorry, another skeleton is unsupported.
VMC4UE is dependent on VRM skeleton.

**Comment by dpredie** [comment]
Thanks for the clarification. Please do consider support for Epic skeleton as it will be flexible for all other avatars in the marketplace
